---
# tasks file for tftpd_hpa
- name: Installing os packages
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ tftpd_hpa_pkgs | default(["tftpd-hpa"]) }}'
    state: present

- name: Configuring...
  become: true
  become_user: root
  with_items:
    - f: tftpd-hpa
      d: /etc/default
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '644'
  notify: TFTP-HPA reconfigured

- name: Start and enable the tftpd-hpa service
  become: true
  become_user: root
  when: tftpd_hpa_config.enabled
  ansible.builtin.service:
    name: tftpd-hpa
    state: started
    enabled: true
